// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef ADWHALESDK_SWIFT_H
#define ADWHALESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdWhaleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdWhaleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// 광고 콘텐츠 등급
/// <code>Sendable</code>: Int 백업 enum 은 본질적으로 동시성 안전하지만, <code>public</code> 타입에는
/// 암묵적 <code>Sendable</code> 이 부여되지 않는다. 선언이 없으면 Swift 6 모드 앱이 이 타입을
/// 전역/static 으로 두는 순간 <code>MutableGlobalVariable</code> 에러가 난다. (2026-09-07 실측)
typedef SWIFT_ENUM(NSInteger, AdWhaleAdContentRating, open) {
  AdWhaleAdContentRatingGeneral = 0,
  AdWhaleAdContentRatingParentalGuidance = 1,
  AdWhaleAdContentRatingTeen = 2,
  AdWhaleAdContentRatingMatureAudience = 3,
};

/// 배너 광고 사이즈
/// <code>Sendable</code>: Int 백업 enum 은 본질적으로 동시성 안전하지만, <code>public</code> 타입에는
/// 암묵적 <code>Sendable</code> 이 부여되지 않는다. 선언이 없으면 Swift 6 모드 앱이 이 타입을
/// 전역/static 으로 두는 순간 <code>MutableGlobalVariable</code> 에러가 난다. (2026-09-07 실측)
typedef SWIFT_ENUM(NSInteger, AdWhaleBannerSize, open) {
  AdWhaleBannerSizeBanner320x50 = 1,
  AdWhaleBannerSizeBanner320x100 = 2,
  AdWhaleBannerSizeBanner300x250 = 4,
  AdWhaleBannerSizeBanner250x250 = 8,
  AdWhaleBannerSizeAdaptiveAnchor = 16,
};

/// GDPR 동의 상태
/// <code>Sendable</code>: Int 백업 enum 은 본질적으로 동시성 안전하지만, <code>public</code> 타입에는
/// 암묵적 <code>Sendable</code> 이 부여되지 않는다. 선언이 없으면 Swift 6 모드 앱이 이 타입을
/// 전역/static 으로 두는 순간 <code>MutableGlobalVariable</code> 에러가 난다. (2026-09-07 실측)
typedef SWIFT_ENUM(NSInteger, AdWhaleGdprConsentStatus, open) {
  AdWhaleGdprConsentStatusUnknown = 0,
  AdWhaleGdprConsentStatusRequired = 1,
  AdWhaleGdprConsentStatusNotRequired = 2,
  AdWhaleGdprConsentStatusObtained = 3,
};

SWIFT_ENUM_FWD_DECL(NSInteger, AdWhaleLogLevel)
/// SDK 로거
SWIFT_CLASS("_TtC10AdWhaleSDK10AdWhaleLog")
@interface AdWhaleLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 로그 레벨 설정 (사용자용).
/// 지정된 레벨을 등록된 각 네트워크 어댑터로 전파한다.
/// 단, config enable_debug 가 켜져 있으면 실제 출력 레벨은 항상 .verbose 로 유지된다.
/// (Android 의 AdWhaleLog.setLogLevel(LogLevel) → LogUtils.setLogLevel → 각 광고 SDK 전파와 동일 개념)
+ (void)setLogLevel:(enum AdWhaleLogLevel)level;
/// 현재 실제 적용 로그 레벨 반환 (config enable_debug 반영)
+ (enum AdWhaleLogLevel)getLogLevel SWIFT_WARN_UNUSED_RESULT;
@end

/// 로그 레벨
/// <code>Sendable</code>: Int 백업 enum 은 본질적으로 동시성 안전하지만, <code>public</code> 타입에는
/// 암묵적 <code>Sendable</code> 이 부여되지 않는다. 선언이 없으면 Swift 6 모드 앱이 이 타입을
/// 전역/static 으로 두는 순간 <code>MutableGlobalVariable</code> 에러가 난다. (2026-09-07 실측)
typedef SWIFT_ENUM(NSInteger, AdWhaleLogLevel, open) {
  AdWhaleLogLevelNone = 0,
  AdWhaleLogLevelError = 1,
  AdWhaleLogLevelWarn = 2,
  AdWhaleLogLevelInfo = 3,
  AdWhaleLogLevelDebug = 4,
  AdWhaleLogLevelVerbose = 5,
};

@class NSString;
@protocol AdWhaleMediationAdBannerViewDelegate;
@class NSCoder;
/// 배너 광고 뷰
/// Android 의 2단계 구조(MediationAdConfigRepository)를 이식한다.
/// <ul>
///   <li>
///     1단계 requestMediationAdConfig(): <code>configReloadSec</code> 주기로 config 를 재요청한다.
///     응답이 유효하지 않으면 isNotAvailableServer=true 일 때만 더미로 폴백,
///     유효하면 config 를 저장하고 2단계(requestAd)를 시작한다.
///   </li>
///   <li>
///     2단계 requestAd(): <code>adReloadSec</code> 주기로 tick(0,1,2…)을 발생시키고,
///     tick 마다 isNotAvailableServer 를 확인해 true 면 testDummyData(),
///     false 면 저장된 config 로 실제 미디에이션 워터폴을 실행한다.
///   </li>
///   <li>
///     resume/pause/stop 플래그가 두 타이머의 실행을 제어한다. (Android resumed/stopped)
///   </li>
/// </ul>
SWIFT_CLASS("_TtC10AdWhaleSDK28AdWhaleMediationAdBannerView")
@interface AdWhaleMediationAdBannerView : UIView
/// 광고 배치 UID
@property (nonatomic, copy) NSString * _Nonnull placementUid;
/// 배너 사이즈
@property (nonatomic) enum AdWhaleBannerSize bannerSize;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleMediationAdBannerViewDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
/// Adaptive Anchor 배너 너비 (0이면 기기 전체 너비)
@property (nonatomic) NSInteger adaptiveAnchorWidth;
/// 이벤트 Delegate 설정
/// <code>delegate</code> 프로퍼티 직접 대입(<code>bannerView.delegate = self</code>)과 동일하며,
/// Objective-C / 래핑 SDK 호출부의 명시적 setter 정합을 위한 편의 메서드입니다.
- (void)setAdWhaleMediationAdBannerViewDelegate:(id <AdWhaleMediationAdBannerViewDelegate> _Nullable)delegate;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 배너의 고유 크기.
/// 매체가 위치 제약(center 등)만 걸고 크기 제약을 생략하면 이 뷰가 0 크기로 레이아웃되고,
/// 광고는 bounds 밖에 그려져(<code>clipsToBounds</code> 기본값이 false 라 보이기는 함) <code>hitTest</code> 가
/// 탭을 거부한다. 광고 SDK 뷰(<code>BannerView</code> 등)와 동일하게 고유 크기를 제공해 이를 막는다.
@property (nonatomic, readonly) CGSize intrinsicContentSize;
/// 배너 광고 로드. 1단계(config) → 2단계(ad) 로 이어진다.
- (void)loadAd;
/// 배너 광고 표시 (숨겨진 배너를 다시 보이게 함)
/// iOS 배너는 <code>loadAd()</code> 성공 시 자동으로 rootView 에 표시됩니다.
/// <code>show()</code> 는 Android SDK 호출 패턴 정합을 위한 편의 메서드이며,
/// 외부에서 뷰를 숨겨 두었다가 다시 노출하는 경우에 유용합니다.
- (void)show;
/// 배너 광고 재개. 일시정지된 config/ad 타이머 동작을 재개한다. (Android resumeTimer)
- (void)resume;
/// 배너 광고 일시정지. config/ad 타이머는 유지되지만 발화 시 작업을 건너뛴다. (Android pauseTimer)
- (void)pause;
/// 배너 광고 정지. config/ad 주기 동작을 완전히 멈춘다. 재개하려면 loadAd() 재호출. (Android stopped)
- (void)stop;
/// 배너 광고 리소스 해제
- (void)destroy;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// 배너 광고 이벤트 Delegate
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK36AdWhaleMediationAdBannerViewDelegate_")
@protocol AdWhaleMediationAdBannerViewDelegate
/// 배너 광고 로드 성공
- (void)bannerDidReceiveAd:(AdWhaleMediationAdBannerView * _Nonnull)bannerView;
/// 배너 광고 로드 실패
- (void)banner:(AdWhaleMediationAdBannerView * _Nonnull)bannerView didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 배너 광고 노출 실패
- (void)banner:(AdWhaleMediationAdBannerView * _Nonnull)bannerView didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 배너 광고 클릭
- (void)bannerDidClick:(AdWhaleMediationAdBannerView * _Nonnull)bannerView;
/// 랜딩 화면 노출
- (void)bannerDidShowLandingScreen:(AdWhaleMediationAdBannerView * _Nonnull)bannerView;
/// 랜딩 화면 닫힘
- (void)bannerDidCloseLandingScreen:(AdWhaleMediationAdBannerView * _Nonnull)bannerView;
/// 배너 광고 타임아웃
- (void)banner:(AdWhaleMediationAdBannerView * _Nonnull)bannerView didTimeoutWithMessage:(NSString * _Nonnull)message;
@end

/// Ad Inspector(광고 검사기) 종료 콜백 Delegate
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK40AdWhaleMediationAdInspectorCloseDelegate_")
@protocol AdWhaleMediationAdInspectorCloseDelegate
/// Ad Inspector 가 닫힐 때 호출됩니다.
/// \param errorCode 에러 코드 (성공 시 0)
///
/// \param errorMessage 에러 메시지 (성공 시 “OK”)
///
- (void)onAdInspectorClosedWithErrorCode:(NSInteger)errorCode errorMessage:(NSString * _Nonnull)errorMessage;
@end

@protocol AdWhaleMediationAdViewDelegate;
/// 일반 배너 광고 뷰
/// 프리로드 배너(<code>AdWhaleMediationAdBannerView</code>, load/show 분리형) 와 달리,
/// 일반 배너는 <code>loadAd()</code> 성공 시 곧바로 자동 노출되며 별도의 <code>show()</code> 호출이 필요 없습니다.
/// (Android <code>AdWhaleMediationAdView</code> 정합)
/// Android 의 2단계 구조(MediationAdConfigRepository)를 이식한다.
/// <ul>
///   <li>
///     1단계 requestMediationAdConfig(): <code>configReloadSec</code> 주기로 config 를 재요청한다.
///     응답이 유효하지 않으면 isNotAvailableServer=true 일 때만 더미로 폴백,
///     유효하면 config 를 저장하고 2단계(requestAd)를 시작한다.
///   </li>
///   <li>
///     2단계 requestAd(): <code>adReloadSec</code> 주기로 tick(0,1,2…)을 발생시키고,
///     tick 마다 isNotAvailableServer 를 확인해 true 면 testDummyData(),
///     false 면 저장된 config 로 실제 미디에이션 워터폴을 실행한다.
///   </li>
///   <li>
///     resume/pause/stop 플래그가 두 타이머의 실행을 제어한다. (Android resumed/stopped)
///   </li>
/// </ul>
SWIFT_CLASS("_TtC10AdWhaleSDK22AdWhaleMediationAdView")
@interface AdWhaleMediationAdView : UIView
/// 광고 배치 UID
@property (nonatomic, copy) NSString * _Nonnull placementUid;
/// 배너 사이즈
@property (nonatomic) enum AdWhaleBannerSize bannerSize;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleMediationAdViewDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
/// Adaptive Anchor 배너 너비 (0이면 기기 전체 너비)
@property (nonatomic) NSInteger adaptiveAnchorWidth;
/// 이벤트 Delegate 설정
/// <code>delegate</code> 프로퍼티 직접 대입(<code>adView.delegate = self</code>)과 동일하며,
/// Objective-C / 래핑 SDK 호출부의 명시적 setter 정합을 위한 편의 메서드입니다.
- (void)setAdWhaleMediationAdViewDelegate:(id <AdWhaleMediationAdViewDelegate> _Nullable)delegate;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 배너의 고유 크기.
/// 매체가 위치 제약(center 등)만 걸고 크기 제약을 생략하면 이 뷰가 0 크기로 레이아웃되고,
/// 광고는 bounds 밖에 그려져(<code>clipsToBounds</code> 기본값이 false 라 보이기는 함) <code>hitTest</code> 가
/// 탭을 거부한다. 광고 SDK 뷰(<code>BannerView</code> 등)와 동일하게 고유 크기를 제공해 이를 막는다.
@property (nonatomic, readonly) CGSize intrinsicContentSize;
/// 배너 광고 로드. 1단계(config) → 2단계(ad) 로 이어지며, 성공 시 자동으로 노출된다.
- (void)loadAd;
/// 배너 광고 재개. 일시정지된 config/ad 타이머 동작을 재개한다. (Android resumeTimer)
- (void)resume;
/// 배너 광고 일시정지. config/ad 타이머는 유지되지만 발화 시 작업을 건너뛴다. (Android pauseTimer)
- (void)pause;
/// 배너 광고 정지. config/ad 주기 동작을 완전히 멈춘다. 재개하려면 loadAd() 재호출. (Android stopped)
- (void)stop;
/// 배너 광고 리소스 해제
- (void)destroy;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// 일반 배너 광고 이벤트 Delegate
/// 프리로드 배너(<code>AdWhaleMediationAdBannerViewDelegate</code>) 와 달리, 일반 배너는
/// <code>loadAd()</code> 성공 시 자동으로 노출되므로 별도의 show / 노출실패 관련 콜백이 없습니다.
/// (Android <code>AdWhaleMediationAdViewListener</code> 정합: onAdLoaded / onAdLoadFailed / onAdClicked)
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK30AdWhaleMediationAdViewDelegate_")
@protocol AdWhaleMediationAdViewDelegate
/// 배너 광고 로드 성공 (로드 직후 자동으로 노출됨)
- (void)adViewDidReceiveAd:(AdWhaleMediationAdView * _Nonnull)adView;
/// 배너 광고 로드 실패
- (void)adView:(AdWhaleMediationAdView * _Nonnull)adView didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 배너 광고 클릭
- (void)adViewDidClick:(AdWhaleMediationAdView * _Nonnull)adView;
@end

@protocol AdWhaleMediationOnInitCompleteDelegate;
SWIFT_ENUM_FWD_DECL(NSInteger, AdWhaleTagForUnderAgeOfConsent)
@class UIViewController;
@protocol AdWhaleMediationGdprConsentDelegate;
/// AdWhale Mediation SDK 메인 진입점
SWIFT_CLASS("_TtC10AdWhaleSDK19AdWhaleMediationAds")
@interface AdWhaleMediationAds : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// QA 검증 전용. 워터폴 앞에서부터 <code>count</code> 개의 광고 네트워크 호출을 건너뛰어
/// 응답이 오지 않는 상태를 만든다. 호출 즉시 반영된다.
/// \param count 0=끔, 1=1순위만 무응답, 99=전 네트워크 무응답
///
+ (void)setQaNoResponseCount:(NSInteger)count;
/// QA 검증 전용. 워치독 제한시간을 강제로 바꾼다. 무응답 유도와는 독립적이라
/// 실제 지연 환경(프록시)에서도 회전을 빠르게 하는 용도로 쓸 수 있다.
/// \param sec 0 이하면 SDK 기본값(<code>defaultAdLoadTimeoutSec</code>)으로 되돌린다.
///
+ (void)setQaAdLoadTimeoutSec:(NSInteger)sec;
/// 워치독이 사용할 제한시간(초). QA override 가 있으면 그 값을 쓴다.
/// config 응답의 <code>timeout_sec</code> 과는 무관한 값이다. (SDK-95 C1)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger adLoadTimeoutSec;)
+ (NSInteger)adLoadTimeoutSec SWIFT_WARN_UNUSED_RESULT;
/// SDK 초기화 (클로저 기반)
/// Publisher UID 는 앱 <code>Info.plist</code> 의 <code>\(AdWhaleConstants.Keys.publisherUid)</code> 키에서 읽는다.
/// 코드에서 직접 전달하려면 <code>initialize(publisherUid:completion:)</code> 오버로드를 사용한다.
+ (void)initializeWithCompletion:(void (^ _Nonnull)(NSInteger, NSString * _Nonnull))completion;
/// SDK 초기화 (Publisher UID 직접 전달 / 클로저 기반)
/// <code>Info.plist</code> 설정 없이 코드에서 Publisher UID 를 넘길 때 사용한다.
/// 파라미터로 받은 값이 우선하며, 빈 문자열이면 <code>Info.plist</code> 값으로 폴백한다.
/// (Android <code>AdWhaleMediationAds.initialize(context, publisherUid, listener)</code> 정합)
+ (void)initializeWithPublisherUid:(NSString * _Nonnull)publisherUid completion:(void (^ _Nonnull)(NSInteger, NSString * _Nonnull))completion;
/// SDK 초기화 (Publisher UID 직접 전달 / Delegate 기반, Objective-C 호환)
+ (void)initializeWithPublisherUid:(NSString * _Nonnull)publisherUid delegate:(id <AdWhaleMediationOnInitCompleteDelegate> _Nonnull)delegate;
/// SDK 초기화 (Delegate 기반, Objective-C 호환)
+ (void)initializeWithDelegate:(id <AdWhaleMediationOnInitCompleteDelegate> _Nonnull)delegate;
/// SDK 초기화 여부
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL initialized;)
+ (BOOL)initialized SWIFT_WARN_UNUSED_RESULT;
/// COPPA 설정
+ (void)setCoppa:(BOOL)isChildDirected;
/// COPPA 적용 여부
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isCoppaApplied;)
+ (BOOL)isCoppaApplied SWIFT_WARN_UNUSED_RESULT;
/// 미성년자 동의 태그 설정
+ (void)setTagForUnderAgeOfConsent:(enum AdWhaleTagForUnderAgeOfConsent)tag;
/// 광고 콘텐츠 등급 설정
+ (void)setMaxAdContentRating:(enum AdWhaleAdContentRating)rating;
/// 테스트 디바이스 ID 설정
+ (void)setTestDeviceIdentifiers:(NSArray<NSString *> * _Nonnull)identifiers;
/// GDPR 동의 요청 (UMP 기반)
+ (void)requestGdprConsentFrom:(UIViewController * _Nonnull)viewController completion:(void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
/// GDPR 동의 요청 (Delegate 기반)
+ (void)requestGdprConsentFrom:(UIViewController * _Nonnull)viewController delegate:(id <AdWhaleMediationGdprConsentDelegate> _Nonnull)delegate;
/// GDPR 동의 상태 초기화 (UMP 리셋 + 저장된 수동 동의 값 제거)
+ (void)resetGdprConsentStatus;
/// GDPR 수동 동의 설정 (non-UMP 네트워크용)
+ (void)setGdpr:(BOOL)hasConsent;
/// GDPR 동의 여부
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL gdprConsent;)
+ (BOOL)gdprConsent SWIFT_WARN_UNUSED_RESULT;
/// GDPR 동의 상태 (UMP 런타임 조회; UMP 초기화 전에는 저장된 값)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum AdWhaleGdprConsentStatus gdprConsentStatus;)
+ (enum AdWhaleGdprConsentStatus)gdprConsentStatus SWIFT_WARN_UNUSED_RESULT;
/// AdMob Ad Inspector(광고 검사기) 실행
/// note:
/// AdMob 어댑터 모듈이 앱에 포함되어 <code>AdWhaleAdMobAdapter.register()</code> 가 호출된 경우에만 동작합니다.
/// \param viewController Inspector 를 표시할 ViewController
///
/// \param completion 종료 콜백 (성공 시 errorCode=0, errorMessage=“OK”)
///
+ (void)openAdInspectorFrom:(UIViewController * _Nonnull)viewController completion:(void (^ _Nonnull)(NSInteger, NSString * _Nonnull))completion;
/// AdMob Ad Inspector 실행 (Delegate 기반, Objective-C 호환)
+ (void)openAdInspectorFrom:(UIViewController * _Nonnull)viewController delegate:(id <AdWhaleMediationAdInspectorCloseDelegate> _Nonnull)delegate;
/// 앱 음소거 설정
+ (void)setAppMuted:(BOOL)isMuted;
/// 앱 볼륨 설정 (0.0 ~ 1.0)
+ (void)setAppVolume:(float)volume;
@end

@protocol AdWhaleMediationAppOpenAdDelegate;
/// 앱오프닝 광고
SWIFT_CLASS("_TtC10AdWhaleSDK25AdWhaleMediationAppOpenAd")
@interface AdWhaleMediationAppOpenAd : NSObject
/// 광고 배치 UID
@property (nonatomic, readonly, copy) NSString * _Nonnull placementUid;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleMediationAppOpenAdDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
- (nonnull instancetype)initWithPlacementUid:(NSString * _Nonnull)placementUid OBJC_DESIGNATED_INITIALIZER;
/// 이벤트 Delegate 설정
/// <code>delegate</code> 프로퍼티 직접 대입(<code>appOpenAd.delegate = self</code>)과 동일하며,
/// Objective-C / 래핑 SDK 호출부의 명시적 setter 정합을 위한 편의 메서드입니다.
- (void)setAdWhaleMediationAppOpenAdDelegate:(id <AdWhaleMediationAppOpenAdDelegate> _Nullable)delegate;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 앱오프닝 광고 로드
- (void)loadAd;
/// 앱오프닝 광고 표시
- (void)showFrom:(UIViewController * _Nonnull)viewController;
/// 광고 준비 여부
@property (nonatomic, readonly) BOOL isAdAvailable;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 앱오프닝 광고 이벤트 Delegate
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK33AdWhaleMediationAppOpenAdDelegate_")
@protocol AdWhaleMediationAppOpenAdDelegate
/// 앱오프닝 광고 로드 성공
- (void)appOpenAdDidLoad:(AdWhaleMediationAppOpenAd * _Nonnull)ad;
/// 앱오프닝 광고 로드 실패
- (void)appOpenAd:(AdWhaleMediationAppOpenAd * _Nonnull)ad didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 앱오프닝 광고 노출 성공
- (void)appOpenAdDidShow:(AdWhaleMediationAppOpenAd * _Nonnull)ad;
/// 앱오프닝 광고 노출 실패
- (void)appOpenAd:(AdWhaleMediationAppOpenAd * _Nonnull)ad didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 앱오프닝 광고 클릭
- (void)appOpenAdDidClick:(AdWhaleMediationAppOpenAd * _Nonnull)ad;
/// 앱오프닝 광고 닫힘
- (void)appOpenAdDidDismiss:(AdWhaleMediationAppOpenAd * _Nonnull)ad;
@end

/// GDPR 동의 처리 콜백
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK35AdWhaleMediationGdprConsentDelegate_")
@protocol AdWhaleMediationGdprConsentDelegate
/// GDPR 동의 처리 완료
/// \param isSuccess 성공 여부
///
/// \param message 결과 메시지
///
- (void)onGdprConsentCompleteWithIsSuccess:(BOOL)isSuccess message:(NSString * _Nonnull)message;
@end

@protocol AdWhaleMediationInterstitialDelegate;
/// 전면 광고
SWIFT_CLASS("_TtC10AdWhaleSDK30AdWhaleMediationInterstitialAd")
@interface AdWhaleMediationInterstitialAd : NSObject
/// 광고 배치 UID
@property (nonatomic, readonly, copy) NSString * _Nonnull placementUid;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleMediationInterstitialDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
- (nonnull instancetype)initWithPlacementUid:(NSString * _Nonnull)placementUid OBJC_DESIGNATED_INITIALIZER;
/// 이벤트 Delegate 설정
/// <code>delegate</code> 프로퍼티 직접 대입(<code>interstitialAd.delegate = self</code>)과 동일하며,
/// Objective-C / 래핑 SDK 호출부의 명시적 setter 정합을 위한 편의 메서드입니다.
- (void)setAdWhaleMediationInterstitialDelegate:(id <AdWhaleMediationInterstitialDelegate> _Nullable)delegate;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 전면 광고 로드
- (void)loadAd;
/// 전면 광고 표시
- (void)showFrom:(UIViewController * _Nonnull)viewController;
/// 전면 광고 취소
- (void)cancelAd;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 전면 광고 이벤트 Delegate
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK36AdWhaleMediationInterstitialDelegate_")
@protocol AdWhaleMediationInterstitialDelegate
/// 전면 광고 로드 성공
- (void)interstitialDidLoad:(AdWhaleMediationInterstitialAd * _Nonnull)ad;
/// 전면 광고 로드 실패
- (void)interstitial:(AdWhaleMediationInterstitialAd * _Nonnull)ad didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 전면 광고 노출 성공
- (void)interstitialDidShow:(AdWhaleMediationInterstitialAd * _Nonnull)ad;
/// 전면 광고 클릭
- (void)interstitialDidClick:(AdWhaleMediationInterstitialAd * _Nonnull)ad;
/// 전면 광고 노출 실패
- (void)interstitial:(AdWhaleMediationInterstitialAd * _Nonnull)ad didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 전면 광고 닫힘
- (void)interstitialDidClose:(AdWhaleMediationInterstitialAd * _Nonnull)ad;
@end

@class UIImageView;
@class UILabel;
@class UIButton;
/// 네이티브 광고 커스텀 바인딩 설정
SWIFT_CLASS("_TtC10AdWhaleSDK37AdWhaleMediationNativeAdBindingHelper")
@interface AdWhaleMediationNativeAdBindingHelper : NSObject
@property (nonatomic, readonly, strong) UIImageView * _Nullable iconView;
@property (nonatomic, readonly, strong) UILabel * _Nullable titleView;
@property (nonatomic, readonly, strong) UILabel * _Nullable bodyView;
@property (nonatomic, readonly, strong) UIButton * _Nullable callToActionView;
@property (nonatomic, readonly, strong) UIView * _Nullable mediaView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 빌더 패턴
SWIFT_CLASS_NAMED("Builder")
@interface AdWhaleMediationNativeAdBindingHelperBuilder : NSObject
- (AdWhaleMediationNativeAdBindingHelperBuilder * _Nonnull)setIconView:(UIImageView * _Nonnull)view;
- (AdWhaleMediationNativeAdBindingHelperBuilder * _Nonnull)setTitleView:(UILabel * _Nonnull)view;
- (AdWhaleMediationNativeAdBindingHelperBuilder * _Nonnull)setBodyView:(UILabel * _Nonnull)view;
- (AdWhaleMediationNativeAdBindingHelperBuilder * _Nonnull)setCallToActionView:(UIButton * _Nonnull)view;
- (AdWhaleMediationNativeAdBindingHelperBuilder * _Nonnull)setMediaView:(UIView * _Nonnull)view;
- (AdWhaleMediationNativeAdBindingHelper * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AdWhaleMediationNativeAdView;
/// 네이티브 광고 이벤트 Delegate
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK32AdWhaleMediationNativeAdDelegate_")
@protocol AdWhaleMediationNativeAdDelegate
/// 네이티브 광고 로드 성공
- (void)nativeAdDidLoad:(AdWhaleMediationNativeAdView * _Nonnull)adView;
/// 네이티브 광고 로드 실패
- (void)nativeAd:(AdWhaleMediationNativeAdView * _Nonnull)adView didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 네이티브 광고 노출 실패
- (void)nativeAd:(AdWhaleMediationNativeAdView * _Nonnull)adView didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 네이티브 광고 클릭
- (void)nativeAdDidClick:(AdWhaleMediationNativeAdView * _Nonnull)adView;
/// 네이티브 광고 닫힘
- (void)nativeAdDidClose:(AdWhaleMediationNativeAdView * _Nonnull)adView;
@end

@class AdWhaleMediationNativeTemplateStyle;
SWIFT_ENUM_FWD_DECL(NSInteger, AdWhaleNativeTemplate)
/// 네이티브 광고 뷰
/// 배너와 동일하게 2단계 리로드 구조를 가진다.
/// <ul>
///   <li>
///     1단계 requestMediationAdConfig(): <code>configReloadSec</code> 주기로 config 를 재요청한다.
///   </li>
///   <li>
///     2단계 requestAd(): <code>adReloadSec</code> 주기로 tick(0,1,2…)을 발생시켜 워터폴(또는 더미)을 재실행한다.
///     고정 템플릿(<code>loadAd(template:)</code>)과 커스텀 바인딩(<code>loadAd(binder:)</code>) 모두 리로드가 적용된다.
///   </li>
/// </ul>
/// 노출 시점은 배너와 달리 <em>매체사가 소유한다.</em> (Android <code>AdWhaleMediationNativeAdView</code> 와 동일)
/// <ul>
///   <li>
///     최초 노출: <code>nativeAdDidLoad(_:)</code> 에서 <code>show()</code> 를 호출해야 화면에 붙는다.
///   </li>
///   <li>
///     갱신 노출: 한 번 <code>show()</code> 된 지면은 <code>isAdShowing</code> 으로 무장되어, 이후 갱신 로드가
///     완료되면 SDK 가 자동으로 교체 노출한다. (매체사가 매번 <code>show()</code> 를 부를 필요 없음)
///   </li>
///   <li>
///     교체는 “새 광고를 붙인 뒤 직전 노출분을 제거” 하는 더블 버퍼 순서로 처리해 지면이 비지 않는다.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC10AdWhaleSDK28AdWhaleMediationNativeAdView")
@interface AdWhaleMediationNativeAdView : UIView
/// 광고 배치 UID
@property (nonatomic, copy) NSString * _Nonnull placementUid;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleMediationNativeAdDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
/// 템플릿 스타일 (템플릿 기반 사용 시)
@property (nonatomic, strong) AdWhaleMediationNativeTemplateStyle * _Nullable templateStyle;
/// 이벤트 Delegate 설정
/// <code>delegate</code> 프로퍼티 직접 대입(<code>nativeAdView.delegate = self</code>)과 동일하며,
/// Objective-C / 래핑 SDK 호출부의 명시적 setter 정합을 위한 편의 메서드입니다.
- (void)setAdWhaleMediationNativeAdDelegate:(id <AdWhaleMediationNativeAdDelegate> _Nullable)delegate;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 템플릿 기반 네이티브 광고 로드 (리로드 포함)
- (void)loadAdWithTemplate:(enum AdWhaleNativeTemplate)template_;
/// 커스텀 바인딩 기반 네이티브 광고 로드 (리로드 포함)
- (void)loadAdWithBinder:(AdWhaleMediationNativeAdBindingHelper * _Nonnull)binder;
/// 네이티브 광고 표시
/// <code>loadAd(template:)</code> / <code>loadAd(binder:)</code> 로 로드한 뒤 <code>nativeAdDidLoad(_:)</code> 에서 호출한다.
/// 한 번 노출된 뒤의 자동 갱신은 SDK 가 알아서 교체 노출하므로 다시 호출할 필요가 없다.
- (void)show;
/// 재개 (일시정지된 리로드 타이머 재개)
- (void)resume;
/// 일시정지 (리로드 타이머 일시정지)
- (void)pause;
/// 정지 (모든 주기 동작 중단). 재개하려면 loadAd 를 다시 호출한다.
- (void)stop;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class UIFont;
/// 네이티브 광고 템플릿 스타일
SWIFT_CLASS("_TtC10AdWhaleSDK35AdWhaleMediationNativeTemplateStyle")
@interface AdWhaleMediationNativeTemplateStyle : NSObject
@property (nonatomic, strong) UIColor * _Nullable mainBackgroundColor;
@property (nonatomic, strong) UIFont * _Nullable callToActionTextFont;
@property (nonatomic, strong) UIColor * _Nullable callToActionTextColor;
@property (nonatomic, strong) UIColor * _Nullable callToActionBackgroundColor;
@property (nonatomic, strong) UIFont * _Nullable primaryTextFont;
@property (nonatomic, strong) UIColor * _Nullable primaryTextColor;
@property (nonatomic, strong) UIColor * _Nullable primaryTextBackgroundColor;
@property (nonatomic, strong) UIFont * _Nullable secondaryTextFont;
@property (nonatomic, strong) UIColor * _Nullable secondaryTextColor;
@property (nonatomic, strong) UIColor * _Nullable secondaryTextBackgroundColor;
@property (nonatomic, strong) UIFont * _Nullable tertiaryTextFont;
@property (nonatomic, strong) UIColor * _Nullable tertiaryTextColor;
@property (nonatomic, strong) UIColor * _Nullable tertiaryTextBackgroundColor;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 빌더 패턴
SWIFT_CLASS_NAMED("Builder")
@interface AdWhaleMediationNativeTemplateStyleBuilder : NSObject
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setMainBackgroundColor:(UIColor * _Nonnull)color;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setCallToActionTextFont:(UIFont * _Nonnull)font;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setCallToActionTextColor:(UIColor * _Nonnull)color;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setCallToActionBackgroundColor:(UIColor * _Nonnull)color;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setPrimaryTextFont:(UIFont * _Nonnull)font;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setPrimaryTextColor:(UIColor * _Nonnull)color;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setPrimaryTextBackgroundColor:(UIColor * _Nonnull)color;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setSecondaryTextFont:(UIFont * _Nonnull)font;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setSecondaryTextColor:(UIColor * _Nonnull)color;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setSecondaryTextBackgroundColor:(UIColor * _Nonnull)color;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setTertiaryTextFont:(UIFont * _Nonnull)font;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setTertiaryTextColor:(UIColor * _Nonnull)color;
- (AdWhaleMediationNativeTemplateStyleBuilder * _Nonnull)setTertiaryTextBackgroundColor:(UIColor * _Nonnull)color;
- (AdWhaleMediationNativeTemplateStyle * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// SDK 초기화 완료 콜백
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK38AdWhaleMediationOnInitCompleteDelegate_")
@protocol AdWhaleMediationOnInitCompleteDelegate
/// SDK 초기화 완료
/// \param statusCode 결과 코드 (100: 성공, 200: 실패)
///
/// \param message 결과 메시지
///
- (void)onInitCompleteWithStatusCode:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@end

@protocol AdWhaleMediationPopupAdDelegate;
/// 팝업 광고
/// iOS 광고 네트워크(AdFit 등)는 종료/전환 구분 없이 단일 Popup 광고 형식만 제공하므로,
/// AdWhale iOS SDK 도 팝업을 하나의 <code>AdWhaleMediationPopupAd</code> 로 통합한다.
SWIFT_CLASS("_TtC10AdWhaleSDK23AdWhaleMediationPopupAd")
@interface AdWhaleMediationPopupAd : NSObject
/// 광고 배치 UID
@property (nonatomic, readonly, copy) NSString * _Nonnull placementUid;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleMediationPopupAdDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
- (nonnull instancetype)initWithPlacementUid:(NSString * _Nonnull)placementUid OBJC_DESIGNATED_INITIALIZER;
/// 이벤트 Delegate 설정
/// <code>delegate</code> 프로퍼티 직접 대입(<code>popupAd.delegate = self</code>)과 동일하며,
/// Objective-C / 래핑 SDK 호출부의 명시적 setter 정합을 위한 편의 메서드입니다.
- (void)setAdWhaleMediationPopupAdDelegate:(id <AdWhaleMediationPopupAdDelegate> _Nullable)delegate;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 버튼 텍스트 커스터마이징
- (void)setCustomizeButtonTextWithPrimaryButtonText:(NSString * _Nonnull)primaryButtonText secondaryButtonText:(NSString * _Nonnull)secondaryButtonText;
/// 설명 텍스트 커스터마이징
- (void)setCustomDescription:(NSString * _Nonnull)descriptionText;
/// 팝업 광고 로드
- (void)loadAd;
/// 팝업 광고 표시
- (void)showFrom:(UIViewController * _Nonnull)viewController;
/// 재개
- (void)resume;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AdWhalePopupCloseReason)
/// 팝업 광고 이벤트 Delegate
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK31AdWhaleMediationPopupAdDelegate_")
@protocol AdWhaleMediationPopupAdDelegate
/// 팝업 광고 로드 성공
- (void)popupAdDidLoad:(AdWhaleMediationPopupAd * _Nonnull)ad;
/// 팝업 광고 로드 실패
- (void)popupAd:(AdWhaleMediationPopupAd * _Nonnull)ad didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 팝업 광고 노출 성공
- (void)popupAdDidShow:(AdWhaleMediationPopupAd * _Nonnull)ad;
/// 팝업 광고 노출 실패
- (void)popupAd:(AdWhaleMediationPopupAd * _Nonnull)ad didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 팝업 광고 클릭
- (void)popupAdDidClick:(AdWhaleMediationPopupAd * _Nonnull)ad;
/// 팝업 광고 닫힘 (사유 포함)
- (void)popupAd:(AdWhaleMediationPopupAd * _Nonnull)ad didCloseWithReason:(enum AdWhalePopupCloseReason)reason;
@end

@class NSNumber;
/// 광고 응답 정보 (어댑터 ↔ 코어 내부 전달용)
/// <em>매체사에게 전달되지 않는다.</em> Android 와 동일하게 로드 성공 콜백은 인자를 받지 않으며
/// (<code>interstitialDidLoad(_:)</code> 등), 이 타입은 어댑터가 워터폴 승자 정보를 코어로 올려
/// 로그·내부 처리에 쓰기 위한 통로다. 어댑터 모듈이 별도 타깃이라 <code>public</code> 이지만
/// 공개 API 표면(델리게이트)에는 노출하지 않는다.
/// (Android <code>net.adwhale.sdk.core.enums.ResponseInfo</code> 와 같은 위치)
SWIFT_CLASS("_TtC10AdWhaleSDK28AdWhaleMediationResponseInfo")
@interface AdWhaleMediationResponseInfo : NSObject
/// 미디에이션 제공자
@property (nonatomic, copy) NSString * _Nullable mediationProvider;
/// 광고 네트워크 이름
@property (nonatomic, copy) NSString * _Nullable adNetworkName;
/// 네트워크 인스턴스 이름
@property (nonatomic, copy) NSString * _Nullable networkInstanceName;
/// 네트워크 인스턴스 ID
@property (nonatomic, copy) NSString * _Nullable networkInstanceId;
/// 수익 (USD, LevelPlay)
@property (nonatomic, strong) NSNumber * _Nullable revenue;
/// 수익 정확도 (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable revenuePrecision;
/// 경매 ID (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable auctionId;
/// 사용자 세그먼트 (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable segmentName;
/// 암호화된 CPM (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable encryptedCPM;
/// A/B 테스트 그룹 (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable abTestGroup;
/// 사용자 국가 코드 (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable country;
/// 응답 추적 ID (AdMob)
@property (nonatomic, copy) NSString * _Nullable responseId;
/// 광고 소스 이름 (AdMob)
@property (nonatomic, copy) NSString * _Nullable adSourceName;
/// 광고 소스 ID (AdMob)
@property (nonatomic, copy) NSString * _Nullable adSourceId;
/// 어댑터 클래스명 (AdMob)
@property (nonatomic, copy) NSString * _Nullable adapterClassName;
/// 응답 지연 시간 밀리초 (AdMob)
@property (nonatomic, strong) NSNumber * _Nullable latencyMillis;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol AdWhaleMediationRewardAdLoadDelegate;
@protocol AdWhaleRewardedFullScreenDelegate;
@protocol AdWhaleUserEarnedRewardDelegate;
/// 리워드 광고
SWIFT_CLASS("_TtC10AdWhaleSDK24AdWhaleMediationRewardAd")
@interface AdWhaleMediationRewardAd : NSObject
/// 광고 배치 UID
@property (nonatomic, readonly, copy) NSString * _Nonnull placementUid;
/// 로드 콜백 Delegate
@property (nonatomic, weak) id <AdWhaleMediationRewardAdLoadDelegate> _Nullable loadDelegate;
/// 전체 화면 콜백 Delegate
@property (nonatomic, weak) id <AdWhaleRewardedFullScreenDelegate> _Nullable fullScreenDelegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
- (nonnull instancetype)initWithPlacementUid:(NSString * _Nonnull)placementUid OBJC_DESIGNATED_INITIALIZER;
/// 전체 화면 콜백 Delegate 설정
/// <code>fullScreenDelegate</code> 프로퍼티 직접 대입과 동일하며,
/// Objective-C / 래핑 SDK 호출부의 명시적 setter 정합을 위한 편의 메서드입니다.
- (void)setAdWhaleRewardedFullScreenDelegate:(id <AdWhaleRewardedFullScreenDelegate> _Nullable)delegate;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// SSV(Server-Side Verification) 사용자 식별자 설정
/// <em>AdMob 전용 API.</em> 로드된 광고 네트워크가 AdMob 인 경우에만 SSV 콜백에 반영되며,
/// 그 외 네트워크에서는 무시된다.
/// 이 객체 생성 이후 <code>show(from:rewardDelegate:)</code> 직전까지 언제든 호출할 수 있고,
/// 여러 번 호출하면 마지막 값이 적용된다. <code>show()</code> 이후 호출은 반영되지 않는다. (ADW-1298)
- (void)setUserId:(NSString * _Nonnull)userId;
/// SSV(Server-Side Verification) 커스텀 데이터 설정
/// <em>AdMob 전용 API.</em> 로드된 광고 네트워크가 AdMob 인 경우에만 SSV 콜백에 반영되며,
/// 그 외 네트워크에서는 무시된다. 전달한 딕셔너리는 JSON 문자열로 직렬화되어
/// SSV 콜백의 <code>custom_data</code> 로 전달된다.
/// 이 객체 생성 이후 <code>show(from:rewardDelegate:)</code> 직전까지 언제든 호출할 수 있고,
/// 여러 번 호출하면 마지막 값이 적용된다. <code>show()</code> 이후 호출은 반영되지 않는다. (ADW-1298)
- (void)setCustomData:(NSDictionary<NSString *, NSString *> * _Nonnull)customData;
/// 리워드 광고 로드
/// \param loadDelegate 로드 결과 콜백 Delegate.
/// (리워드 로드 Delegate 는 세터가 아닌 <code>loadAd(loadDelegate:)</code> 파라미터로 받는다)
///
- (void)loadAdWithLoadDelegate:(id <AdWhaleMediationRewardAdLoadDelegate> _Nonnull)loadDelegate;
/// 리워드 광고 표시
- (void)showFrom:(UIViewController * _Nonnull)viewController rewardDelegate:(id <AdWhaleUserEarnedRewardDelegate> _Nonnull)rewardDelegate;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 리워드 광고 로드 콜백
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK36AdWhaleMediationRewardAdLoadDelegate_")
@protocol AdWhaleMediationRewardAdLoadDelegate
/// 리워드 광고 로드 성공
- (void)rewardedAdDidLoad:(AdWhaleMediationRewardAd * _Nonnull)ad;
/// 리워드 광고 로드 실패
- (void)rewardedAd:(AdWhaleMediationRewardAd * _Nonnull)ad didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@end

/// 리워드 보상 아이템
SWIFT_CLASS("_TtC10AdWhaleSDK26AdWhaleMediationRewardItem")
@interface AdWhaleMediationRewardItem : NSObject
/// 보상 유형
@property (nonatomic, readonly, copy) NSString * _Nonnull rewardType;
/// 보상 수량
@property (nonatomic, readonly) NSInteger rewardAmount;
- (nonnull instancetype)initWithRewardType:(NSString * _Nonnull)rewardType rewardAmount:(NSInteger)rewardAmount OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 네이티브 광고 템플릿 유형
/// <code>Sendable</code>: Int 백업 enum 은 본질적으로 동시성 안전하지만, <code>public</code> 타입에는
/// 암묵적 <code>Sendable</code> 이 부여되지 않는다. 선언이 없으면 Swift 6 모드 앱이 이 타입을
/// 전역/static 으로 두는 순간 <code>MutableGlobalVariable</code> 에러가 난다. (2026-09-07 실측)
typedef SWIFT_ENUM(NSInteger, AdWhaleNativeTemplate, open) {
  AdWhaleNativeTemplateSmall = 1,
  AdWhaleNativeTemplateMedium = 2,
  AdWhaleNativeTemplateFullscreen = 4,
};

/// 팝업 광고 닫기 사유
/// <code>Sendable</code>: Int 백업 enum 은 본질적으로 동시성 안전하지만, <code>public</code> 타입에는
/// 암묵적 <code>Sendable</code> 이 부여되지 않는다. 선언이 없으면 Swift 6 모드 앱이 이 타입을
/// 전역/static 으로 두는 순간 <code>MutableGlobalVariable</code> 에러가 난다. (2026-09-07 실측)
typedef SWIFT_ENUM(NSInteger, AdWhalePopupCloseReason, open) {
  AdWhalePopupCloseReasonUnknown = 0,
  AdWhalePopupCloseReasonPrimaryButton = 1,
  AdWhalePopupCloseReasonSecondaryButton = 2,
  AdWhalePopupCloseReasonOutsideTouch = 4,
  AdWhalePopupCloseReasonBackPress = 8,
  AdWhalePopupCloseReasonTodayDismiss = 16,
  AdWhalePopupCloseReasonAmbiguousCancel = 32,
};

/// SDK 결과 코드
/// <code>Sendable</code>: Int 백업 enum 은 본질적으로 동시성 안전하지만, <code>public</code> 타입에는
/// 암묵적 <code>Sendable</code> 이 부여되지 않는다. 선언이 없으면 Swift 6 모드 앱이 이 타입을
/// 전역/static 으로 두는 순간 <code>MutableGlobalVariable</code> 에러가 난다. (2026-09-07 실측)
typedef SWIFT_ENUM(NSInteger, AdWhaleResultCode, open) {
  AdWhaleResultCodeInternalSuccess = 100,
  AdWhaleResultCodeInternalError = 200,
  AdWhaleResultCodeMediationNetworkError = 300,
  AdWhaleResultCodeMediationNetworkSuccess = 400,
};

/// 리워드 광고 전체 화면 콜백
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK33AdWhaleRewardedFullScreenDelegate_")
@protocol AdWhaleRewardedFullScreenDelegate
@optional
/// 리워드 광고 노출 성공
- (void)rewardedAdDidShow:(AdWhaleMediationRewardAd * _Nonnull)ad;
/// 리워드 광고 클릭
- (void)rewardedAdDidClick:(AdWhaleMediationRewardAd * _Nonnull)ad;
/// 리워드 광고 닫힘
- (void)rewardedAdDidDismiss:(AdWhaleMediationRewardAd * _Nonnull)ad;
/// 리워드 광고 노출 실패
- (void)rewardedAd:(AdWhaleMediationRewardAd * _Nonnull)ad didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@end

/// 미성년자 동의 태그
/// <code>Sendable</code>: Int 백업 enum 은 본질적으로 동시성 안전하지만, <code>public</code> 타입에는
/// 암묵적 <code>Sendable</code> 이 부여되지 않는다. 선언이 없으면 Swift 6 모드 앱이 이 타입을
/// 전역/static 으로 두는 순간 <code>MutableGlobalVariable</code> 에러가 난다. (2026-09-07 실측)
typedef SWIFT_ENUM(NSInteger, AdWhaleTagForUnderAgeOfConsent, open) {
  AdWhaleTagForUnderAgeOfConsentUnspecified = 0,
  AdWhaleTagForUnderAgeOfConsentNo = 1,
  AdWhaleTagForUnderAgeOfConsentYes = 2,
};

/// 사용자 보상 콜백
/// <code>@MainActor</code>: SDK 는 모든 콜백을 메인 스레드로 마샬링해 전달한다. 이 선언은
/// 새 제약을 만드는 게 아니라 이미 참인 사실을 적는 것이다. 선언이 없으면 Swift 6
/// 모드 앱이 <code>@MainActor</code> 타입으로 채택할 때 <code>ConformanceIsolation</code> 에러가 난다.
/// <code>@preconcurrency</code>: 기존 매체사 앱이 <code>@MainActor</code> 아닌 타입으로 채택 중이면
/// 에러 대신 런타임 검사로 완화된다. (2026-09-07 Xcode 27 실측)
SWIFT_PROTOCOL("_TtP10AdWhaleSDK31AdWhaleUserEarnedRewardDelegate_")
@protocol AdWhaleUserEarnedRewardDelegate
/// 사용자 보상 지급
- (void)userDidEarnReward:(AdWhaleMediationRewardItem * _Nonnull)rewardItem;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
