// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef ADWHALESDK_SWIFT_H
#define ADWHALESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdWhaleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// 광고 콘텐츠 등급
typedef SWIFT_ENUM(NSInteger, AdWhaleAdContentRating, open) {
  AdWhaleAdContentRatingGeneral = 0,
  AdWhaleAdContentRatingParentalGuidance = 1,
  AdWhaleAdContentRatingTeen = 2,
  AdWhaleAdContentRatingMatureAudience = 3,
};

@class NSString;
@protocol AdWhaleAppOpenAdDelegate;
@class UIViewController;
/// 앱오프닝 광고
SWIFT_CLASS("_TtC10AdWhaleSDK16AdWhaleAppOpenAd")
@interface AdWhaleAppOpenAd : NSObject
/// 광고 배치 UID
@property (nonatomic, readonly, copy) NSString * _Nonnull placementUid;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleAppOpenAdDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
- (nonnull instancetype)initWithPlacementUid:(NSString * _Nonnull)placementUid OBJC_DESIGNATED_INITIALIZER;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 앱오프닝 광고 로드
- (void)loadAd;
/// 앱오프닝 광고 표시
- (void)showFrom:(UIViewController * _Nonnull)viewController;
/// 광고 준비 여부
@property (nonatomic, readonly) BOOL isAdAvailable;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 앱오프닝 광고 이벤트 Delegate
SWIFT_PROTOCOL("_TtP10AdWhaleSDK24AdWhaleAppOpenAdDelegate_")
@protocol AdWhaleAppOpenAdDelegate
/// 앱오프닝 광고 로드 성공
- (void)appOpenAdDidLoad:(AdWhaleAppOpenAd * _Nonnull)ad;
/// 앱오프닝 광고 로드 실패
- (void)appOpenAd:(AdWhaleAppOpenAd * _Nonnull)ad didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 앱오프닝 광고 노출 성공
- (void)appOpenAdDidShow:(AdWhaleAppOpenAd * _Nonnull)ad;
/// 앱오프닝 광고 노출 실패
- (void)appOpenAd:(AdWhaleAppOpenAd * _Nonnull)ad didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 앱오프닝 광고 클릭
- (void)appOpenAdDidClick:(AdWhaleAppOpenAd * _Nonnull)ad;
/// 앱오프닝 광고 닫힘
- (void)appOpenAdDidDismiss:(AdWhaleAppOpenAd * _Nonnull)ad;
@end

@class AdWhaleBannerView;
/// 배너 광고 이벤트 Delegate
SWIFT_PROTOCOL("_TtP10AdWhaleSDK21AdWhaleBannerDelegate_")
@protocol AdWhaleBannerDelegate
/// 배너 광고 로드 성공
- (void)bannerDidReceiveAd:(AdWhaleBannerView * _Nonnull)bannerView;
/// 배너 광고 로드 실패
- (void)banner:(AdWhaleBannerView * _Nonnull)bannerView didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 배너 광고 노출 실패
- (void)banner:(AdWhaleBannerView * _Nonnull)bannerView didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 배너 광고 클릭
- (void)bannerDidClick:(AdWhaleBannerView * _Nonnull)bannerView;
/// 랜딩 화면 노출
- (void)bannerDidShowLandingScreen:(AdWhaleBannerView * _Nonnull)bannerView;
/// 랜딩 화면 닫힘
- (void)bannerDidCloseLandingScreen:(AdWhaleBannerView * _Nonnull)bannerView;
/// 배너 광고 타임아웃
- (void)banner:(AdWhaleBannerView * _Nonnull)bannerView didTimeoutWithMessage:(NSString * _Nonnull)message;
@end

/// 배너 광고 사이즈
typedef SWIFT_ENUM(NSInteger, AdWhaleBannerSize, open) {
  AdWhaleBannerSizeBanner320x50 = 1,
  AdWhaleBannerSizeBanner320x100 = 2,
  AdWhaleBannerSizeBanner300x250 = 4,
  AdWhaleBannerSizeBanner250x250 = 8,
  AdWhaleBannerSizeAdaptiveAnchor = 16,
};

@class NSCoder;
/// 배너 광고 뷰
SWIFT_CLASS("_TtC10AdWhaleSDK17AdWhaleBannerView")
@interface AdWhaleBannerView : UIView
/// 광고 배치 UID
@property (nonatomic, copy) NSString * _Nonnull placementUid;
/// 배너 사이즈
@property (nonatomic) enum AdWhaleBannerSize bannerSize;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleBannerDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
/// Adaptive Anchor 배너 너비 (0이면 기기 전체 너비)
@property (nonatomic) NSInteger adaptiveAnchorWidth;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 배너 광고 로드
- (void)loadAd;
/// 배너 광고 재개
- (void)resume;
/// 배너 광고 일시정지
- (void)pause;
/// 배너 광고 리소스 해제
- (void)destroy;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// GDPR 동의 처리 콜백
SWIFT_PROTOCOL("_TtP10AdWhaleSDK26AdWhaleGdprConsentDelegate_")
@protocol AdWhaleGdprConsentDelegate
/// GDPR 동의 처리 완료
/// \param isSuccess 성공 여부
///
/// \param message 결과 메시지
///
- (void)onGdprConsentCompleteWithIsSuccess:(BOOL)isSuccess message:(NSString * _Nonnull)message;
@end

/// GDPR 동의 상태
typedef SWIFT_ENUM(NSInteger, AdWhaleGdprConsentStatus, open) {
  AdWhaleGdprConsentStatusUnknown = 0,
  AdWhaleGdprConsentStatusRequired = 1,
  AdWhaleGdprConsentStatusNotRequired = 2,
  AdWhaleGdprConsentStatusObtained = 3,
};

/// SDK 초기화 완료 콜백
SWIFT_PROTOCOL("_TtP10AdWhaleSDK27AdWhaleInitCompleteDelegate_")
@protocol AdWhaleInitCompleteDelegate
/// SDK 초기화 완료
/// \param statusCode 결과 코드 (100: 성공, 200: 실패)
///
/// \param message 결과 메시지
///
- (void)onInitCompleteWithStatusCode:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@end

@protocol AdWhaleInterstitialDelegate;
/// 전면 광고
SWIFT_CLASS("_TtC10AdWhaleSDK21AdWhaleInterstitialAd")
@interface AdWhaleInterstitialAd : NSObject
/// 광고 배치 UID
@property (nonatomic, readonly, copy) NSString * _Nonnull placementUid;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleInterstitialDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
- (nonnull instancetype)initWithPlacementUid:(NSString * _Nonnull)placementUid OBJC_DESIGNATED_INITIALIZER;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 전면 광고 로드
- (void)loadAd;
/// 전면 광고 표시
- (void)showFrom:(UIViewController * _Nonnull)viewController;
/// 전면 광고 취소
- (void)cancelAd;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 전면 광고 이벤트 Delegate
SWIFT_PROTOCOL("_TtP10AdWhaleSDK27AdWhaleInterstitialDelegate_")
@protocol AdWhaleInterstitialDelegate
/// 전면 광고 로드 성공
- (void)interstitialDidLoad:(AdWhaleInterstitialAd * _Nonnull)ad;
/// 전면 광고 로드 실패
- (void)interstitial:(AdWhaleInterstitialAd * _Nonnull)ad didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 전면 광고 노출 성공
- (void)interstitialDidShow:(AdWhaleInterstitialAd * _Nonnull)ad;
/// 전면 광고 클릭
- (void)interstitialDidClick:(AdWhaleInterstitialAd * _Nonnull)ad;
/// 전면 광고 노출 실패
- (void)interstitial:(AdWhaleInterstitialAd * _Nonnull)ad didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 전면 광고 닫힘
- (void)interstitialDidClose:(AdWhaleInterstitialAd * _Nonnull)ad;
@end

enum AdWhaleLogLevel : NSInteger;
/// SDK 로거
SWIFT_CLASS("_TtC10AdWhaleSDK10AdWhaleLog")
@interface AdWhaleLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 로그 레벨 설정
+ (void)setLogLevel:(enum AdWhaleLogLevel)level;
/// 현재 로그 레벨 반환
+ (enum AdWhaleLogLevel)getLogLevel SWIFT_WARN_UNUSED_RESULT;
@end

/// 로그 레벨
typedef SWIFT_ENUM(NSInteger, AdWhaleLogLevel, open) {
  AdWhaleLogLevelNone = 0,
  AdWhaleLogLevelError = 1,
  AdWhaleLogLevelWarn = 2,
  AdWhaleLogLevelInfo = 3,
  AdWhaleLogLevelDebug = 4,
  AdWhaleLogLevelVerbose = 5,
};

enum AdWhaleTagForUnderAgeOfConsent : NSInteger;
/// AdWhale Mediation SDK 메인 진입점
SWIFT_CLASS("_TtC10AdWhaleSDK19AdWhaleMediationAds")
@interface AdWhaleMediationAds : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// SDK 초기화 (클로저 기반)
+ (void)initializeWithCompletion:(void (^ _Nonnull)(NSInteger, NSString * _Nonnull))completion;
/// SDK 초기화 (Delegate 기반, Objective-C 호환)
+ (void)initializeWithDelegate:(id <AdWhaleInitCompleteDelegate> _Nonnull)delegate;
/// SDK 초기화 여부
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL initialized;)
+ (BOOL)initialized SWIFT_WARN_UNUSED_RESULT;
/// 서버 환경 설정 (초기화 전에 호출)
+ (void)setEnvironmentWithUseUAT:(BOOL)useUAT;
/// COPPA 설정
+ (void)setCoppa:(BOOL)isChildDirected;
/// COPPA 적용 여부
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isCoppaApplied;)
+ (BOOL)isCoppaApplied SWIFT_WARN_UNUSED_RESULT;
/// 미성년자 동의 태그 설정
+ (void)setTagForUnderAgeOfConsent:(enum AdWhaleTagForUnderAgeOfConsent)tag;
/// 광고 콘텐츠 등급 설정
+ (void)setMaxAdContentRating:(enum AdWhaleAdContentRating)rating;
/// 테스트 디바이스 ID 설정
+ (void)setTestDeviceIdentifiers:(NSArray<NSString *> * _Nonnull)identifiers;
/// GDPR 동의 요청 (UMP 기반)
+ (void)requestGdprConsentFrom:(UIViewController * _Nonnull)viewController completion:(void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
/// GDPR 동의 요청 (Delegate 기반)
+ (void)requestGdprConsentFrom:(UIViewController * _Nonnull)viewController delegate:(id <AdWhaleGdprConsentDelegate> _Nonnull)delegate;
/// GDPR 동의 상태 초기화
+ (void)resetGdprConsentStatus;
/// GDPR 수동 동의 설정 (non-UMP 네트워크용)
+ (void)setGdpr:(BOOL)hasConsent;
/// GDPR 동의 여부
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL gdprConsent;)
+ (BOOL)gdprConsent SWIFT_WARN_UNUSED_RESULT;
/// GDPR 동의 상태
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum AdWhaleGdprConsentStatus gdprConsentStatus;)
+ (enum AdWhaleGdprConsentStatus)gdprConsentStatus SWIFT_WARN_UNUSED_RESULT;
/// 앱 음소거 설정
+ (void)setAppMuted:(BOOL)isMuted;
/// 앱 볼륨 설정 (0.0 ~ 1.0)
+ (void)setAppVolume:(float)volume;
@end

@class UIImageView;
@class UILabel;
@class UIButton;
/// 네이티브 광고 커스텀 바인딩 설정
SWIFT_CLASS("_TtC10AdWhaleSDK21AdWhaleNativeAdBinder")
@interface AdWhaleNativeAdBinder : NSObject
@property (nonatomic, readonly, strong) UIImageView * _Nullable iconView;
@property (nonatomic, readonly, strong) UILabel * _Nullable titleView;
@property (nonatomic, readonly, strong) UILabel * _Nullable bodyView;
@property (nonatomic, readonly, strong) UIButton * _Nullable callToActionView;
@property (nonatomic, readonly, strong) UIView * _Nullable mediaView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 빌더 패턴
SWIFT_CLASS("_TtCC10AdWhaleSDK21AdWhaleNativeAdBinder7Builder")
@interface Builder : NSObject
- (Builder * _Nonnull)setIconView:(UIImageView * _Nonnull)view;
- (Builder * _Nonnull)setTitleView:(UILabel * _Nonnull)view;
- (Builder * _Nonnull)setBodyView:(UILabel * _Nonnull)view;
- (Builder * _Nonnull)setCallToActionView:(UIButton * _Nonnull)view;
- (Builder * _Nonnull)setMediaView:(UIView * _Nonnull)view;
- (AdWhaleNativeAdBinder * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AdWhaleNativeAdView;
/// 네이티브 광고 이벤트 Delegate
SWIFT_PROTOCOL("_TtP10AdWhaleSDK23AdWhaleNativeAdDelegate_")
@protocol AdWhaleNativeAdDelegate
/// 네이티브 광고 로드 성공
- (void)nativeAdDidLoad:(AdWhaleNativeAdView * _Nonnull)adView;
/// 네이티브 광고 로드 실패
- (void)nativeAd:(AdWhaleNativeAdView * _Nonnull)adView didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 네이티브 광고 노출 실패
- (void)nativeAd:(AdWhaleNativeAdView * _Nonnull)adView didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 네이티브 광고 클릭
- (void)nativeAdDidClick:(AdWhaleNativeAdView * _Nonnull)adView;
/// 네이티브 광고 닫힘
- (void)nativeAdDidClose:(AdWhaleNativeAdView * _Nonnull)adView;
@end

@class AdWhaleNativeTemplateStyle;
enum AdWhaleNativeTemplate : NSInteger;
/// 네이티브 광고 뷰
SWIFT_CLASS("_TtC10AdWhaleSDK19AdWhaleNativeAdView")
@interface AdWhaleNativeAdView : UIView
/// 광고 배치 UID
@property (nonatomic, copy) NSString * _Nonnull placementUid;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhaleNativeAdDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
/// 템플릿 스타일 (템플릿 기반 사용 시)
@property (nonatomic, strong) AdWhaleNativeTemplateStyle * _Nullable templateStyle;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 템플릿 기반 네이티브 광고 로드
- (void)loadAdWithTemplate:(enum AdWhaleNativeTemplate)template_;
/// 커스텀 바인딩 기반 네이티브 광고 로드
- (void)loadAdWithBinder:(AdWhaleNativeAdBinder * _Nonnull)binder;
/// 네이티브 광고 표시
- (void)show;
/// 재개
- (void)resume;
/// 일시정지
- (void)pause;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// 네이티브 광고 템플릿 유형
typedef SWIFT_ENUM(NSInteger, AdWhaleNativeTemplate, open) {
  AdWhaleNativeTemplateSmall = 1,
  AdWhaleNativeTemplateMedium = 2,
  AdWhaleNativeTemplateFullscreen = 4,
};

@class UIColor;
@class UIFont;
/// 네이티브 광고 템플릿 스타일
SWIFT_CLASS("_TtC10AdWhaleSDK26AdWhaleNativeTemplateStyle")
@interface AdWhaleNativeTemplateStyle : NSObject
@property (nonatomic, strong) UIColor * _Nullable mainBackgroundColor;
@property (nonatomic, strong) UIFont * _Nullable callToActionTextFont;
@property (nonatomic, strong) UIColor * _Nullable callToActionTextColor;
@property (nonatomic, strong) UIColor * _Nullable callToActionBackgroundColor;
@property (nonatomic, strong) UIFont * _Nullable primaryTextFont;
@property (nonatomic, strong) UIColor * _Nullable primaryTextColor;
@property (nonatomic, strong) UIColor * _Nullable primaryTextBackgroundColor;
@property (nonatomic, strong) UIFont * _Nullable secondaryTextFont;
@property (nonatomic, strong) UIColor * _Nullable secondaryTextColor;
@property (nonatomic, strong) UIColor * _Nullable secondaryTextBackgroundColor;
@property (nonatomic, strong) UIFont * _Nullable tertiaryTextFont;
@property (nonatomic, strong) UIColor * _Nullable tertiaryTextColor;
@property (nonatomic, strong) UIColor * _Nullable tertiaryTextBackgroundColor;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 빌더 패턴
SWIFT_CLASS("_TtCC10AdWhaleSDK26AdWhaleNativeTemplateStyle7Builder")
@interface Builder : NSObject
- (Builder * _Nonnull)setMainBackgroundColor:(UIColor * _Nonnull)color;
- (Builder * _Nonnull)setCallToActionTextFont:(UIFont * _Nonnull)font;
- (Builder * _Nonnull)setCallToActionTextColor:(UIColor * _Nonnull)color;
- (Builder * _Nonnull)setCallToActionBackgroundColor:(UIColor * _Nonnull)color;
- (Builder * _Nonnull)setPrimaryTextFont:(UIFont * _Nonnull)font;
- (Builder * _Nonnull)setPrimaryTextColor:(UIColor * _Nonnull)color;
- (Builder * _Nonnull)setPrimaryTextBackgroundColor:(UIColor * _Nonnull)color;
- (Builder * _Nonnull)setSecondaryTextFont:(UIFont * _Nonnull)font;
- (Builder * _Nonnull)setSecondaryTextColor:(UIColor * _Nonnull)color;
- (Builder * _Nonnull)setSecondaryTextBackgroundColor:(UIColor * _Nonnull)color;
- (Builder * _Nonnull)setTertiaryTextFont:(UIFont * _Nonnull)font;
- (Builder * _Nonnull)setTertiaryTextColor:(UIColor * _Nonnull)color;
- (Builder * _Nonnull)setTertiaryTextBackgroundColor:(UIColor * _Nonnull)color;
- (AdWhaleNativeTemplateStyle * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum AdWhalePopupAdType : NSInteger;
@protocol AdWhalePopupAdDelegate;
/// 팝업 광고 (종료/전환 공용)
SWIFT_CLASS("_TtC10AdWhaleSDK14AdWhalePopupAd")
@interface AdWhalePopupAd : NSObject
/// 광고 배치 UID
@property (nonatomic, readonly, copy) NSString * _Nonnull placementUid;
/// 팝업 유형
@property (nonatomic, readonly) enum AdWhalePopupAdType popupType;
/// 이벤트 Delegate
@property (nonatomic, weak) id <AdWhalePopupAdDelegate> _Nullable delegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
- (nonnull instancetype)initWithPlacementUid:(NSString * _Nonnull)placementUid popupType:(enum AdWhalePopupAdType)popupType OBJC_DESIGNATED_INITIALIZER;
/// 종료 팝업 광고 편의 생성자
+ (AdWhalePopupAd * _Nonnull)exitPopupWithPlacementUid:(NSString * _Nonnull)placementUid SWIFT_WARN_UNUSED_RESULT;
/// 전환 팝업 광고 편의 생성자
+ (AdWhalePopupAd * _Nonnull)transitionPopupWithPlacementUid:(NSString * _Nonnull)placementUid SWIFT_WARN_UNUSED_RESULT;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 버튼 텍스트 커스터마이징 (종료 팝업 전용)
- (void)setCustomizeButtonTextWithPrimaryButtonText:(NSString * _Nonnull)primaryButtonText secondaryButtonText:(NSString * _Nonnull)secondaryButtonText;
/// 설명 텍스트 커스터마이징 (종료 팝업 전용)
- (void)setCustomDescription:(NSString * _Nonnull)descriptionText;
/// 팝업 광고 로드
- (void)loadAd;
/// 팝업 광고 표시
- (void)showFrom:(UIViewController * _Nonnull)viewController;
/// 재개
- (void)resume;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum AdWhalePopupCloseReason : NSInteger;
/// 팝업 광고(종료/전환) 이벤트 Delegate
SWIFT_PROTOCOL("_TtP10AdWhaleSDK22AdWhalePopupAdDelegate_")
@protocol AdWhalePopupAdDelegate
/// 팝업 광고 로드 성공
- (void)popupAdDidLoad:(AdWhalePopupAd * _Nonnull)ad;
/// 팝업 광고 로드 실패
- (void)popupAd:(AdWhalePopupAd * _Nonnull)ad didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@optional
/// 팝업 광고 노출 성공
- (void)popupAdDidShow:(AdWhalePopupAd * _Nonnull)ad;
/// 팝업 광고 노출 실패
- (void)popupAd:(AdWhalePopupAd * _Nonnull)ad didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
/// 팝업 광고 클릭
- (void)popupAdDidClick:(AdWhalePopupAd * _Nonnull)ad;
/// 팝업 광고 닫힘 (사유 포함)
- (void)popupAd:(AdWhalePopupAd * _Nonnull)ad didCloseWithReason:(enum AdWhalePopupCloseReason)reason;
@end

/// 팝업 광고 유형
typedef SWIFT_ENUM(NSInteger, AdWhalePopupAdType, open) {
  AdWhalePopupAdTypeExit = 0,
  AdWhalePopupAdTypeTransition = 1,
};

/// 팝업 광고 닫기 사유
typedef SWIFT_ENUM(NSInteger, AdWhalePopupCloseReason, open) {
  AdWhalePopupCloseReasonUnknown = 0,
  AdWhalePopupCloseReasonPrimaryButton = 1,
  AdWhalePopupCloseReasonSecondaryButton = 2,
  AdWhalePopupCloseReasonOutsideTouch = 4,
  AdWhalePopupCloseReasonBackPress = 8,
  AdWhalePopupCloseReasonTodayDismiss = 16,
  AdWhalePopupCloseReasonAmbiguousCancel = 32,
};

@class NSNumber;
/// 광고 응답 정보
SWIFT_CLASS("_TtC10AdWhaleSDK19AdWhaleResponseInfo")
@interface AdWhaleResponseInfo : NSObject
/// 미디에이션 제공자
@property (nonatomic, copy) NSString * _Nullable mediationProvider;
/// 광고 네트워크 이름
@property (nonatomic, copy) NSString * _Nullable adNetworkName;
/// 네트워크 인스턴스 이름
@property (nonatomic, copy) NSString * _Nullable networkInstanceName;
/// 네트워크 인스턴스 ID
@property (nonatomic, copy) NSString * _Nullable networkInstanceId;
/// 수익 (USD, LevelPlay)
@property (nonatomic, strong) NSNumber * _Nullable revenue;
/// 수익 정확도 (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable revenuePrecision;
/// 경매 ID (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable auctionId;
/// 사용자 세그먼트 (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable segmentName;
/// 암호화된 CPM (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable encryptedCPM;
/// A/B 테스트 그룹 (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable abTestGroup;
/// 사용자 국가 코드 (LevelPlay)
@property (nonatomic, copy) NSString * _Nullable country;
/// 응답 추적 ID (AdMob)
@property (nonatomic, copy) NSString * _Nullable responseId;
/// 광고 소스 이름 (AdMob)
@property (nonatomic, copy) NSString * _Nullable adSourceName;
/// 광고 소스 ID (AdMob)
@property (nonatomic, copy) NSString * _Nullable adSourceId;
/// 어댑터 클래스명 (AdMob)
@property (nonatomic, copy) NSString * _Nullable adapterClassName;
/// 응답 지연 시간 밀리초 (AdMob)
@property (nonatomic, strong) NSNumber * _Nullable latencyMillis;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// SDK 결과 코드
typedef SWIFT_ENUM(NSInteger, AdWhaleResultCode, open) {
  AdWhaleResultCodeInternalSuccess = 100,
  AdWhaleResultCodeInternalError = 200,
  AdWhaleResultCodeMediationNetworkError = 300,
  AdWhaleResultCodeMediationNetworkSuccess = 400,
};

/// 리워드 보상 아이템
SWIFT_CLASS("_TtC10AdWhaleSDK17AdWhaleRewardItem")
@interface AdWhaleRewardItem : NSObject
/// 보상 유형
@property (nonatomic, readonly, copy) NSString * _Nonnull rewardType;
/// 보상 수량
@property (nonatomic, readonly) NSInteger rewardAmount;
- (nonnull instancetype)initWithRewardType:(NSString * _Nonnull)rewardType rewardAmount:(NSInteger)rewardAmount OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol AdWhaleRewardedAdLoadDelegate;
@protocol AdWhaleRewardedFullScreenDelegate;
@protocol AdWhaleUserEarnedRewardDelegate;
/// 리워드 광고
SWIFT_CLASS("_TtC10AdWhaleSDK17AdWhaleRewardedAd")
@interface AdWhaleRewardedAd : NSObject
/// 광고 배치 UID
@property (nonatomic, readonly, copy) NSString * _Nonnull placementUid;
/// 로드 콜백 Delegate
@property (nonatomic, weak) id <AdWhaleRewardedAdLoadDelegate> _Nullable loadDelegate;
/// 전체 화면 콜백 Delegate
@property (nonatomic, weak) id <AdWhaleRewardedFullScreenDelegate> _Nullable fullScreenDelegate;
/// 지역 타겟팅 (Cauly)
@property (nonatomic, copy) NSString * _Nullable region;
/// LevelPlay 배치 이름
@property (nonatomic, copy) NSString * _Nullable placementName;
- (nonnull instancetype)initWithPlacementUid:(NSString * _Nonnull)placementUid OBJC_DESIGNATED_INITIALIZER;
/// 좌표 기반 타겟팅 설정
- (void)setGeocoderWithLatitude:(double)latitude longitude:(double)longitude;
/// 리워드 광고 로드
- (void)loadAd;
/// 리워드 광고 표시
- (void)showFrom:(UIViewController * _Nonnull)viewController rewardDelegate:(id <AdWhaleUserEarnedRewardDelegate> _Nonnull)rewardDelegate;
/// 리소스 해제
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 리워드 광고 로드 콜백
SWIFT_PROTOCOL("_TtP10AdWhaleSDK29AdWhaleRewardedAdLoadDelegate_")
@protocol AdWhaleRewardedAdLoadDelegate
/// 리워드 광고 로드 성공
- (void)rewardedAdDidLoad:(AdWhaleRewardedAd * _Nonnull)ad;
/// 리워드 광고 로드 실패
- (void)rewardedAd:(AdWhaleRewardedAd * _Nonnull)ad didFailToLoadWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@end

/// 리워드 광고 전체 화면 콜백
SWIFT_PROTOCOL("_TtP10AdWhaleSDK33AdWhaleRewardedFullScreenDelegate_")
@protocol AdWhaleRewardedFullScreenDelegate
@optional
/// 리워드 광고 노출 성공
- (void)rewardedAdDidShow:(AdWhaleRewardedAd * _Nonnull)ad;
/// 리워드 광고 클릭
- (void)rewardedAdDidClick:(AdWhaleRewardedAd * _Nonnull)ad;
/// 리워드 광고 닫힘
- (void)rewardedAdDidDismiss:(AdWhaleRewardedAd * _Nonnull)ad;
/// 리워드 광고 노출 실패
- (void)rewardedAd:(AdWhaleRewardedAd * _Nonnull)ad didFailToShowWithError:(NSInteger)statusCode message:(NSString * _Nonnull)message;
@end

/// 미성년자 동의 태그
typedef SWIFT_ENUM(NSInteger, AdWhaleTagForUnderAgeOfConsent, open) {
  AdWhaleTagForUnderAgeOfConsentUnspecified = 0,
  AdWhaleTagForUnderAgeOfConsentNo = 1,
  AdWhaleTagForUnderAgeOfConsentYes = 2,
};

/// 사용자 보상 콜백
SWIFT_PROTOCOL("_TtP10AdWhaleSDK31AdWhaleUserEarnedRewardDelegate_")
@protocol AdWhaleUserEarnedRewardDelegate
/// 사용자 보상 지급
- (void)userDidEarnReward:(AdWhaleRewardItem * _Nonnull)rewardItem;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
